# Generated by Django 3.2.16 on 2023-12-07 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20231207_1006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'verbose_name': 'Рецепт в списке покупок', 'verbose_name_plural': 'Рецепты в списках покупок'},
        ),
    ]
