# Generated by Django 3.2.16 on 2023-12-07 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Время приготовления'),
        ),
    ]
