# Generated by Django 3.2.16 on 2023-12-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20231219_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipes_images', verbose_name='Фото'),
        ),
    ]
